version: '3.8'

services:
  # --- 1. CARREGADOR DE DADES (Init Container) ---
  git_loader:
    image: alpine/git
    container_name: db_seeder
    command: sh -c "git clone https://github.com/0xRh4ps00dy/scripts-db /temp && cp /temp/*.js /init-data/"
    volumes:
      - db_init_files:/init-data

  # --- 2. BASE DE DADES (MongoDB) ---
  mongo_db:
    image: mongo:latest
    container_name: db_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo_data:/data/db
      - db_init_files:/docker-entrypoint-initdb.d
    depends_on:
      git_loader:
        condition: service_completed_successfully
    networks:
      - app-network

  # --- 3. GESTOR WEB (Mongo Express) ---
  mongo_express:
    image: mongo-express:latest
    container_name: db_client_web
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongo_db:27017/
    depends_on:
      - mongo_db
    networks:
      - app-network

  # --- 4. APLICACIÃ“ (Node.js) ---
  node_app:
    build: ./app
    container_name: backend_node
    restart: always
    environment:
      DB_HOST: mongo_db
    depends_on:
      - mongo_db
    networks:
      - app-network

  # --- 5. SERVIDOR WEB (Nginx) ---
  webserver:
    image: nginx:alpine
    container_name: web_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node_app
    networks:
      - app-network

volumes:
  mongo_data:
  db_init_files: # Volum temporal per passar scripts

networks:
  app-network:
    driver: bridge